### ISSUE TITLE
Update readme with Python 3 pickle example

### ISSUE THREAD

**Issue by ahlaw** [czhuang/JSB-Chorales-dataset#3]
The cPickle module has been replaced by the pickle module in Python 3. Also, when using the Python 3 pickle module, "latin1" encoding will need to be specified when loading the data since it decodes the data as ascii by default.

**Comment by cooijmanstim** [comment]
Thank you, I did finally get around to updating this. I also went ahead and converted everything to JSON to prevent future head-scratching :sweat_smile:
